from __future__ import annotations

from typing import Any, Final


# Closed action vocabulary. Each parameter can occur under exactly one compatible action family.
ACTION_CONTRACTS: Final[dict[str, dict[str, Any]]] = {
    "preserve_existing": {
        "required_parameter_keys": (),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": (),
        "required_permissions": (),
    },
    "inspect_only": {
        "required_parameter_keys": (),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": (),
        "required_permissions": (),
    },
    "configure_layout": {
        "required_parameter_keys": ("layout_model",),
        "optional_parameter_keys": ("gap", "alignment", "direction"),
        "aliases": {"layout": "layout_model"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": (),
    },
    "set_style": {
        "required_parameter_keys": ("properties",),
        "optional_parameter_keys": (),
        "aliases": {"style": "properties"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": (),
    },
    "apply_class": {
        "required_parameter_keys": (),
        "optional_parameter_keys": (
            "class_names",
            "remove_classes",
            "replace_classes",
        ),
        "aliases": {
            "class_name": "class_names",
            "add_classes": "class_names",
            "remove_class": "remove_classes",
            "remove_class_names": "remove_classes",
            "replace_class": "replace_classes",
            "rename_class": "replace_classes",
            "class_replacements": "replace_classes",
        },
        "derived_class_effects": ("class_assignment", "approved_class_set_change"),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_class_permission_when_set_changes",),
    },
    "configure_overlay": {
        "required_parameter_keys": (
            "containment_model",
            "positioning_model",
            "stacking_model",
        ),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("geometry", "overlay_strategy"),
        "required_permissions": (),
    },
    "set_responsive": {
        "required_parameter_keys": ("layout_adaptation",),
        "optional_parameter_keys": ("breakpoint_strategy", "target_identity", "viewports"),
        "aliases": {"breakpoints": "breakpoint_strategy", "layout": "layout_adaptation"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("responsive_strategy", "responsive_behavior"),
        "required_permissions": (),
    },
    "configure_interaction": {
        "required_parameter_keys": ("interaction_model",),
        "optional_parameter_keys": ("event", "target_identity"),
        "aliases": {"interaction": "interaction_model"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": ("interaction_behavior",),
        "required_claims": (
            "interaction_approval",
            "accessibility_strategy",
            "accessibility",
            "interaction_validation",
        ),
        "required_permissions": ("architect_interaction_approval",),
    },
    "bind_dynamic_loop": {
        "required_parameter_keys": ("binding_map",),
        "optional_parameter_keys": (),
        "aliases": {"bindings": "binding_map"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": ("dynamic_loop_binding",),
        "required_claims": ("dynamic_loop_approval",),
        "required_permissions": ("architect_dynamic_loop_approval",),
    },
    "attach_asset": {
        "required_parameter_keys": ("asset_ref",),
        "optional_parameter_keys": ("placement",),
        "aliases": {"asset_id": "asset_ref"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("asset_source",),
        "required_permissions": (),
    },
    "use_placeholder": {
        "required_parameter_keys": ("placeholder_policy",),
        "optional_parameter_keys": (),
        "aliases": {"policy": "placeholder_policy"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("placeholder_policy",),
        "required_permissions": (),
    },
    "set_ui_control": {
        "required_parameter_keys": ("control_path",),
        "optional_parameter_keys": (),
        "aliases": {"ui_control_path": "control_path"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("ui_control_path",),
        "required_permissions": (),
    },
    "run_qa": {
        "required_parameter_keys": ("qa_scope",),
        "optional_parameter_keys": ("target_identity",),
        "aliases": {"suite": "qa_scope"},
        "derived_class_effects": (),
        "derived_structure_effects": (),
        "derived_decision_effects": (),
        "required_claims": ("QA",),
        "required_permissions": (),
    },
    "create_element": {
        "required_parameter_keys": ("produced_node_id", "parent_node_id", "element_type"),
        "optional_parameter_keys": (),
        "aliases": {"new_node_id": "produced_node_id"},
        "derived_class_effects": (),
        "derived_structure_effects": ("node_creation", "parent_child_change"),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "remove_element": {
        "required_parameter_keys": (),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": ("node_removal",),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "delete_element": {
        "required_parameter_keys": (),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": ("node_removal",),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "reparent_element": {
        "required_parameter_keys": ("new_parent_node_id",),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": ("parent_child_change",),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "move_element": {
        "required_parameter_keys": ("new_parent_node_id",),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": ("parent_child_change",),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "replace_element": {
        "required_parameter_keys": ("replacement_node_id",),
        "optional_parameter_keys": ("element_type",),
        "aliases": {"new_node_id": "replacement_node_id"},
        "derived_class_effects": (),
        "derived_structure_effects": ("node_replacement", "identity_change"),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
    "rename_node": {
        "required_parameter_keys": ("new_node_id",),
        "optional_parameter_keys": (),
        "aliases": {},
        "derived_class_effects": (),
        "derived_structure_effects": ("identity_change",),
        "derived_decision_effects": (),
        "required_claims": ("geometry",),
        "required_permissions": ("architect_structure_permission",),
    },
}


_EFFECT_KEYS: Final[set[str]] = {
    "class_name",
    "class_names",
    "add_classes",
    "remove_class",
    "remove_classes",
    "remove_class_names",
    "replace_class",
    "replace_classes",
    "rename_class",
    "class_replacements",
    "produced_node_id",
    "new_node_id",
    "replacement_node_id",
    "parent_node_id",
    "new_parent_node_id",
    "element_type",
    "requires_decision",
    "decision_required",
}


def contract_for(action_type: str) -> dict[str, Any] | None:
    return ACTION_CONTRACTS.get(action_type)


def effect_parameter_keys() -> set[str]:
    return set(_EFFECT_KEYS)


__all__ = ["ACTION_CONTRACTS", "contract_for", "effect_parameter_keys"]
